name: Ora
options:
  bundleIdPrefix: com.orabrowser
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0
targets:
   ora:
      type: application
      platform: "macOS"
      deploymentTarget: "14.0"
      sources:
        - path: ora
      resources:
        - path: ora/Modules/EmojiPicker/emoji-set.json
        - path: ora/Resources
          optional: true
      dependencies:
        - package: Sparkle
      
      preBuildScripts:
        - name: "Copy Icon Bundle"
          script: |
            if [ "$CONFIGURATION" = "Debug" ]; then
                echo "Using OraIconDev.icon for Debug build"
                cp -R "$SRCROOT/Icons/OraIconDev.icon" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Resources/"
            else
                echo "Using OraIcon.icon for Release build" 
                cp -R "$SRCROOT/Icons/OraIcon.icon" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Resources/"
            fi

      settings:
        base:
           SWIFT_VERSION: 5.9
           CODE_SIGN_STYLE: Automatic
           MARKETING_VERSION: 0.0.62
           CURRENT_PROJECT_VERSION: 62
           PRODUCT_NAME: Ora
           PRODUCT_BUNDLE_IDENTIFIER: com.orabrowser.ora
           GENERATE_INFOPLIST_FILE: YES
           SUFeedURL: "https://the-ora.github.io/browser/appcast.xml"
           SUPublicEDKey: "Ozj+rezzbJAD76RfajtfQ7rFojJbpFSCl/0DcFSBCTI="
           SUEnableAutomaticChecks: YES

