name: Ora
options:
  bundleIdPrefix: com.orabrowser
targets:
   ora:
      type: application
      platform: "macOS"
      deploymentTarget: "14.0"
      sources:
        - path: ora
      resources:
        - path: ora/Modules/EmojiPicker/emoji-set.json
        - path: ora/Resources
          optional: true
      dependencies:
        - package: Sparkle

      settings:
        base:
           SWIFT_VERSION: 5.9
           CODE_SIGN_STYLE: Automatic
           MARKETING_VERSION: 0.0.60
           CURRENT_PROJECT_VERSION: 60
           PRODUCT_NAME: Ora
           PRODUCT_BUNDLE_IDENTIFIER: com.orabrowser.ora
           GENERATE_INFOPLIST_FILE: YES
           SUFeedURL: "https://the-ora.github.io/browser/appcast.xml"
           SUPublicEDKey: "Ozj+rezzbJAD76RfajtfQ7rFojJbpFSCl/0DcFSBCTI="
           SUEnableAutomaticChecks: YES

