name: Ora
options:
  bundleIdPrefix: com.orabrowser
targets:
  ora:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ora
    settings:
      base:
        SWIFT_VERSION: 5.9
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_NAME: Ora
        PRODUCT_BUNDLE_IDENTIFIER: com.orabrowser.ora
        GENERATE_INFOPLIST_FILE: YES